//LOCALHOST
###
GET http://localhost:8080/contacts

###
GET http://localhost:8080/contacts/6636d99c393a9360e22fe60e

###
GET http://localhost:8080/contacts/6636da12393a9360e230a163

###
GET http://localhost:8080/contacts/6636da20393a9360e230b7a6

//PRODUCTION
###
GET https://cse341-node-2-jtrh.onrender.com/contacts

###
GET https://cse341-node-2-jtrh.onrender.com/contacts/6636d99c393a9360e22fe60e

###
GET https://cse341-node-2-jtrh.onrender.com/contacts/6636da12393a9360e230a163

###
GET https://cse341-node-2-jtrh.onrender.com/contacts/6636da20393a9360e230b7a6