//LOCALHOST
###
GET http://localhost:8080/contacts HTTP/1.1

###
GET http://localhost:8080/contacts/6636d99c393a9360e22fe60e HTTP/1.1

###
GET http://localhost:8080/contacts/6636da12393a9360e230a163 HTTP/1.1

###
GET http://localhost:8080/contacts/6636da20393a9360e230b7a6 HTTP/1.1

//PRODUCTION
###
GET https://cse341-node-2-jtrh.onrender.com/contacts HTTP/1.1

###
GET https://cse341-node-2-jtrh.onrender.com/contacts/6636d99c393a9360e22fe60e HTTP/1.1

###
GET https://cse341-node-2-jtrh.onrender.com/contacts/6636da12393a9360e230a163 HTTP/1.1

###
GET https://cse341-node-2-jtrh.onrender.com/contacts/6636da20393a9360e230b7a6 HTTP/1.1